default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webauthn_demo_development

test:
  <<: *default
  database: webauthn_demo_test

production:
  <<: *default
  database: webauthn_demo_production
  username: webauthn_demo
  password: <%= ENV["WEBAUTHN_DEMO_DATABASE_PASSWORD"] %>
